#! /bin/sh -f

args=''
incdirs=''

for arg in ` echo "$CPLUS_INCLUDE_PATH" | tr : ' ' `
do
  incdirs="$incdirs '-I$arg'"
done

for arg
do
  case "$arg" in
  -I*)
    incdirs="$incdirs '$arg'"
    ;;
  *)
    args="$args '$arg'"
    ;;
  esac
done

eval "c++ $incdirs   -Wall -Wwrite-strings -fno-strict-aliasing -D_REENTRANT -D_GNU_SOURCE   -DPIC -fPIC $args"
exit $?
